// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R5B
// for Lénárd Nagy (elnrnag@elx78355y6x) on Mon Apr  1 13:32:37 2019

// Copyright (c) 2000-2018 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "S1APPort.hh"

namespace LibS1AP__Interface {

S1APPort::S1APPort(const char *par_port_name)
	: S1APPort_BASE(par_port_name)
{

}

S1APPort::~S1APPort()
{

}

void S1APPort::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void S1APPort::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void S1APPort::Handle_Fd_Event_Error(int /*fd*/)
{

}

void S1APPort::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void S1APPort::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void S1APPort::Handle_Timeout(double time_since_last_call) {}*/

void S1APPort::user_map(const char * /*system_port*/)
{

}

void S1APPort::user_unmap(const char * /*system_port*/)
{

}

void S1APPort::user_start()
{

}

void S1APPort::user_stop()
{

}

void S1APPort::outgoing_send(const LibS1AP__TitanExtensions::S1AP__PDUWithConnId& /*send_par*/)
{

}

} /* end of namespace */

